### ISSUE TITLE
Lower coverage produced by Tracer-x compared to KLEE

### ISSUE THREAD

**Issue by feliciahalim** [tracer-x/klee#115]
We currently look at the coverage as an indicator for comparing the Tracer-x and KLEE performance. However, Tracer-x seems produce lower line coverage (also branch and instruction coverage). It might be caused by paths are subsumed and therefore it is not executed.  

Therefore, we might need other way to comparing Tracer-X and KLEE performance such as only subsumed the non-error paths, so we could expect number of error-paths generated by Tracer-X and KLEE is  similar (that shows we didn't miss the error)

**Comment by domainexpert** [comment]
@feliciahalim In theory, subsumption should not result in lower coverage, because subsumption means that it is not worth re-traversing the subsuming node as at most we would only get the same information (i.e., explore the same code). Let's discuss the issue on error paths that you mentioned. It sometimes happen that Tracer-X KLEE and standard KLEE report the same set of errors, yet standard KLEE reports more error paths. This does not mean that the standard KLEE has better coverage, because theoretically, the additional error paths would just re-traverse the parts of code that have been traversed by the subsuming error paths.

This is because an interpolant `Itp` that is stored as an entry in the subsumption table is an over-approximation of the program state `S` that reaches a particular control point `PC`. Say continuing  the symbolic execution from `PC` with state `S` results in `n` error (sub-)paths. An interpolant `Itp` for `PC`, which is weaker (an over-approximation) of `S` guarantees that the (sub-)path conditions leading to those errors are still feasible, when the execution from `PC` instead starts with `Itp` in place of `S`. Say there is an execution path again reaching control point `PC` with state `S1`, and `S1` implies the interpolant `Itp` already stored in the table, therefore this execution path can be subsumed. Because `S1` is a stronger formula than the interpolant `Itp` (`S1` implies `Itp`), it is not possible for it to have more error paths than the `n` already traversed from `PC` with starting state `Itp` (or the original `S`). `S1` can only have less error paths than the set of `n`.

I suppose you used timeouts when running Tracer-X KLEE and standard KLEE, so perhaps this is more of a performance issue: Given the same time bound, Tracer-X KLEE explores less code.

**Comment by feliciahalim** [comment]
@domainexpert yes, I have used timeouts when running Tracer-X KLEE and standard KLEE. Thank you for restating the problem, Tracer-X KLEE might explores less code in the same time bound. Do you have any suggestion where to start to investigate why the coverage is lower? or any ideas to improving the coverage.

**Comment by domainexpert** [comment]
@feliciahalim One way to improve the coverage is to improve the speed. Please refer to issues #71, #65, #28, and #85, and possibly others.

**Comment by domainexpert** [comment]
@feliciahalim Another way is to instrument to code using `klee_join` at appropriate locations so that we get more subsumptions and increase the exploration speed.

**Comment by domainexpert** [comment]
There is a more focused discussion in #175.
