### ISSUE TITLE
Cubic time problem

### ISSUE THREAD

**Issue by feliciahalim** [tracer-x/klee#65]
This issue is assigned to also assigned to @domainexpert

**Comment by feliciahalim** [comment]
Last time I have tried to change the data structure of `storesList` from `vector` to `hashmap`. However, the execution time doesn't much improved.

**Comment by domainexpert** [comment]
@feliciahalim Thank you for your excellent efforts. After merging PR #64 to `trfix3` branch it seems this is no longer a major issue. It seems now in `trfix3` solver calls are back to be the no. 1 bottleneck.

**Comment by domainexpert** [comment]
@feliciahalim I realize there is no explanation on the issue at all in this conversation. So here is the issue: Given path of length `n`, `getAllVersionedAllocations()` traverses the path and gets O(`n`) allocations, and then for each allocation, O(`n`) `stores()` is called. Hence, we have within `getSingletonExpressions` O(`n^2`) operation. Now, there are O(`n`) subsumption checks along a path, since we stop for subsumption check at every start of a basic block along the path, and each time `getSingletonExpression()` is called, and hence the complexity of the algorithm is greater than O(`n^3`), which is really bad. 

@feliciahalim mentioned a possible mitigation of the issue. For `storeList` field, can we change it to map instead of vector because in `Dependency.cpp` line 741 it iterates to find the suitable allocation so if we change it to map it become [allocation, list of StorageCells] so we just need to find the key allocation, ad get all the elements we need. @feliciahalim has tried to change the data structure of `storesList` from vector to `hashmap`. However, the execution time doesn't much improved. 

After merging PR #64 to trfix3 branch it seems this is no longer a major issue. It seems now in `trfix3` solver calls are back to be the no. 1 bottleneck.

**Comment by domainexpert** [comment]
@feliciahalim However, this issue shouldn't be ignored and should be fixed in the future, as the call to `getSingletonExpression` is still the more expensive of others.

**Comment by domainexpert** [comment]
An idea is to reuse more from KLEE's execution state if possible, which should probably contain all allocations and their expressions, although not the core (interpolant) markings.

**Comment by domainexpert** [comment]
This issue is partially mitigated by #68.

**Comment by domainexpert** [comment]
It is also partially mitigated by #67 .

**Comment by domainexpert** [comment]
The parts of the code mentioned are no longer there.
